# Generated by Django 6.0.1 on 2026-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0004_product_remove_cartitem_product_id_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
